// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mobileInfo_Assignment03.Data;

#nullable disable

namespace mobileInfo_Assignment03.Migrations
{
    [DbContext(typeof(mobileInfo_Assignment03Context))]
    partial class mobileInfo_Assignment03ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("mobileInfo_Assignment03.Models.mobileInfo", b =>
                {
                    b.Property<int>("mobileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mobileId"));

                    b.Property<string>("manufacturedYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobileColour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobileCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobileModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mobileStorage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("mobileId");

                    b.ToTable("mobileInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
